### ISSUE TITLE
Consider adding carlbarrdahl/swish Node lib for Swish

### ISSUE THREAD

**Issue by buren** [buren/awesome-sweden#15]
See https://github.com/carlbarrdahl/swish-payments

**Comment by buren** [comment]
@carlbarrdahl sorry for pinging you like this, but it would be really valuable to have a listed Swish implementation in JavaScript. Would you consider your library stable enough to be listed here?

Thanks!

**Comment by carlbarrdahl** [comment]
Hey! Thanks for mentioning this library, however I don't actively maintain this repo so there's no guarantee it will still work if Swish decides to change things up. 

If someone wants to maintain it I'd be happy to transfer the ownership.

**Comment by buren** [comment]
Cool. I think I'll add it, with a note saying that its not actively being maintained, since its certainly a good starting point 👍 

Thanks!
